#!/bin/bash
#
#	@(#)	[MB] aj_diff_tree	Version 1.2 du 18/04/21 - 
#

usage()
{
	echo "Usage : $PRGM dir1 dir2 [file]"
}

err_exit()
{
	retcode="$1"
	shift
	echo "$PRGM : $@" >&2
	exit "$retcode"
}

clean()
{
	rm "$TMP_LIST1" "$TMP_LIST2"
	rm "$TMP_INFO1" "$TMP_INFO2"
}

list()
{
	find . -type f -print | sed 's|^\./||' | sort
}

infos()
{
	IFS='|'
	if [ "$1" = "" -o "$2" != "" ]; then
		err_exit 126 "infos() : parameters error [$@]"
	fi

	file="$1"

	MD5=`md5sum "$file" | sed 's/[ 	].*$//'`
	SIZE=`stat -c "%s" "$file"`
	DATE_S=`stat -c '%Y' "$file"`
	DATE=`stat -c '%y' "$file" | sed 's/\..*//;s/ /_/'`
}

disp_infos()
{
	IFS='|'
	while read "file"
	do
		infos "$file"
		printf "%-30s %15d %32s %10d %s\n" "$file" "$SIZE" "$MD5" "$DATE_S" "$DATE"
	done
}

TMP_LIST1="/tmp/list1.$$"
TMP_LIST2="/tmp/list2.$$"

TMP_INFO1="/tmp/info1.$$"
TMP_INFO2="/tmp/info2.$$"

trap 'clean' 1 2 3 10 11 12 15

PRGM=`basename "$0"`
dir1="$1"
dir2="$2"

if [ "$2" = "" -o "$4" != "" ]; then
	usage
	exit 1
fi

if [ "$3" != "" ]; then
	file="$3"
	diff "$dir1/$file" "$dir2/$file"
	exit $?
fi

CWD=`pwd`

# Get infos for files of dir1
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd "$dir1" > /dev/null || err_exit 1 "cannot change directory to \"$dir1\" !"
	list > "$TMP_LIST1"
	cat "$TMP_LIST1" | disp_infos > "$TMP_INFO1"
cd "$CWD" > /dev/null

# Get infos for files of dir2
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
cd "$dir2" > /dev/null || err_exit 1 "cannot change directory to \"$dir2\" !"
	list > "$TMP_LIST2"
	cat "$TMP_LIST2" | disp_infos > "$TMP_INFO2"
cd "$CWD" > /dev/null

join -a 1 -a 2 -j 1 -e '---' -o '0 1.2 2.2 1.3 2.3 1.4 2.4 1.5 2.5' "$TMP_INFO1" "$TMP_INFO2" | awk 'BEGIN {
	sz_filename	= -10;
	sz_size		=  10;
	sz_MD5		= -32;
	sz_epoch		=  10;
	sz_date		= -19;
}
{
	if ($4 == $5) {
		marker	= "=";
	}
	else if ($6 < $7) {
		marker	= ">";
	}
	else if ($6 > $7) {
		marker	= "<";
	}
	else {
		marker	= "!";
	}
	printf("%s %*s %*s %*s %*s %*s %*s %*s\n",			\
	       marker,									\
		  sz_filename, $1,							\
	       sz_size, $2, sz_size, $3,					\
		  sz_MD5,  $4, sz_MD5,  $5,					\
		  sz_date, $8, sz_date, $9);
}'

clean
